Repository Sykander/iterable-async, pull requests merged in 2019-12, with the labels that each got.

#22 Package Name
  package.json
Labels: bug, documentation

#23 Pre Publish
  package.json
Labels: documentation

#24 Readme
  README.md
Labels: documentation

#25 For Each Docs
  README.md
  docs/playground.js
  package.json
Labels: documentation, enhancement

#26 Release 1.0.1
  README.md
  docs/playground.js
  package.json
Labels: documentation, enhancement

#40 Async array
  src/async-array.js
  src/index.js
  test/async-array.spec.js
Labels: enhancement

#41 Async Array Docs
  README.md
  docs/playground.js
Labels: documentation

#47 Release 1.0.2
  README.md
  docs/playground.js
  package.json
  src/async-array.js
  src/async-for-each.js
  src/async-map.js
  src/index.js
  test/async-array.spec.js
Labels: enhancement

#51 Package keywords
  package-lock.json
  package.json
Labels: documentation, enhancement

#53 Update README.md
  README.md
Labels: documentation

#55 Async sort specs
  test/async-filter.spec.js
  test/async-find-index.spec.js
  test/async-find.spec.js
  test/async-for-each.spec.js
  test/async-map.spec.js
  test/async-sort.spec.js
  test/support/helpers.js
Labels: enhancement

#57 Async Sort Specs
  test/async-array.spec.js
Labels: bug

#58 Async sort
  README.md
  docs/playground.js
  src/async-array.js
  src/async-filter.js
  src/async-find-index.js
  src/async-find.js
  src/async-for-each.js
  src/async-map.js
  src/async-quick-sort.js
  src/async-sort.js
  src/helpers.js
  src/index.js
  test/async-sort.spec.js
Labels: documentation, enhancement

#60 Async Sort
  README.md
  src/async-sort.js
  src/helpers.js
Labels: bug, documentation, enhancement

#65 thisArg
  src/async-filter.js
  src/async-find-index.js
  src/async-find.js
  src/async-for-each.js
  src/async-map.js
  src/async-sort.js
  test/async-filter.spec.js
  test/async-find-index.spec.js
  test/async-find.spec.js
  test/async-for-each.spec.js
  test/async-map.spec.js
  test/support/constants.js
  test/support/helpers.js
Labels: bug, enhancement

#70 Empty Entries
  src/async-filter.js
  src/async-for-each.js
  src/async-map.js
  src/helpers.js
Labels: bug
